[2025-08-18_00-35-01.893][START full BACKUP]
[POC] Criando FULL backup em /backups/full_2025-08-18_00-35-01.893
[2025-08-18_00-35-01.893][START incremental BACKUP]
[POC] Nenhum full encontrado, criando full primeiro.
[2025-08-18_00-35-01.895][START full BACKUP]
[POC] Criando FULL backup em /backups/full_2025-08-18_00-35-01.895
2025-08-18T00:35:01.903788-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized server arguments: --datadir=/var/lib/mysql 
2025-08-18T00:35:01.903932-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --target-dir=/backups/full_2025-08-18_00-35-01.893 --host=db --user=root --password=* 
xtrabackup version 8.0.35-34 based on MySQL server 8.0.35 Linux (x86_64) (revision id: c8a25ff9)
2025-08-18T00:35:01.907606-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized server arguments: --datadir=/var/lib/mysql 
2025-08-18T00:35:01.907741-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --target-dir=/backups/full_2025-08-18_00-35-01.895 --host=db --user=root --password=* 
xtrabackup version 8.0.35-34 based on MySQL server 8.0.35 Linux (x86_64) (revision id: c8a25ff9)
250818 00:35:01  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup;host=db' as 'root'  (using password: YES).
250818 00:35:01  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup;host=db' as 'root'  (using password: YES).
Failed to connect to MySQL server: DBI connect(';mysql_read_default_group=xtrabackup;host=db','root',...) failed: Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection. at - line 1536.
Failed to connect to MySQL server: DBI connect(';mysql_read_default_group=xtrabackup;host=db','root',...) failed: Authentication plugin 'caching_sha2_password' reported error: Authentication requires secure connection. at - line 1536.
2025-08-18T00:35:01.960802-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: db, user: root, password: set, port: not set, socket: not set
2025-08-18T00:35:01.962864-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: db, user: root, password: set, port: not set, socket: not set
2025-08-18T00:35:01.980261-00:00 0 [Note] [MY-011825] [Xtrabackup] Using server version 8.0.41
2025-08-18T00:35:01.981272-00:00 0 [Note] [MY-011825] [Xtrabackup] Using server version 8.0.41
2025-08-18T00:35:01.983228-00:00 0 [Note] [MY-011825] [Xtrabackup] Executing LOCK INSTANCE FOR BACKUP ...
2025-08-18T00:35:01.983228-00:00 0 [Note] [MY-011825] [Xtrabackup] Executing LOCK INSTANCE FOR BACKUP ...
2025-08-18T00:35:01.983722-00:00 0 [Note] [MY-011825] [Xtrabackup] uses posix_fadvise().
2025-08-18T00:35:01.983756-00:00 0 [Note] [MY-011825] [Xtrabackup] cd to /var/lib/mysql
2025-08-18T00:35:01.983773-00:00 0 [Note] [MY-011825] [Xtrabackup] open files limit requested 0, set to 1024
2025-08-18T00:35:01.983778-00:00 0 [Note] [MY-011825] [Xtrabackup] uses posix_fadvise().
2025-08-18T00:35:01.983798-00:00 0 [Note] [MY-011825] [Xtrabackup] cd to /var/lib/mysql
2025-08-18T00:35:01.983816-00:00 0 [Note] [MY-011825] [Xtrabackup] open files limit requested 0, set to 1024
2025-08-18T00:35:01.994657-00:00 0 [Note] [MY-011825] [Xtrabackup] using the following InnoDB configuration:
2025-08-18T00:35:01.994661-00:00 0 [Note] [MY-011825] [Xtrabackup] using the following InnoDB configuration:
2025-08-18T00:35:01.994720-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_data_home_dir = .
2025-08-18T00:35:01.994720-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_data_home_dir = .
2025-08-18T00:35:01.994729-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_data_file_path = ibdata1:12M:autoextend
2025-08-18T00:35:01.994729-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_data_file_path = ibdata1:12M:autoextend
2025-08-18T00:35:01.994751-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_group_home_dir = ./
2025-08-18T00:35:01.994752-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_group_home_dir = ./
2025-08-18T00:35:01.994758-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_files_in_group = 2
2025-08-18T00:35:01.994760-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_files_in_group = 2
2025-08-18T00:35:01.994779-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_file_size = 50331648
2025-08-18T00:35:01.994779-00:00 0 [Note] [MY-011825] [Xtrabackup] innodb_log_file_size = 50331648
2025-08-18T00:35:01.996564-00:00 0 [Note] [MY-011825] [Xtrabackup] inititialize_service_handles suceeded
2025-08-18T00:35:01.996575-00:00 0 [Note] [MY-011825] [Xtrabackup] inititialize_service_handles suceeded
2025-08-18T00:35:02.047380-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: db, user: root, password: set, port: not set, socket: not set
2025-08-18T00:35:02.049395-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: db, user: root, password: set, port: not set, socket: not set
2025-08-18T00:35:02.060073-00:00 0 [Note] [MY-011825] [Xtrabackup] Redo Log Archiving is not set up.
2025-08-18T00:35:02.060779-00:00 0 [Note] [MY-011825] [Xtrabackup] Redo Log Archiving is not set up.
2025-08-18T00:35:02.147654-00:00 0 [ERROR] [MY-011825] [Xtrabackup] cannot mkdir: 2 /backups/full_2025-08-18_00-35-01.893/
2025-08-18T00:35:02.149668-00:00 0 [ERROR] [MY-011825] [Xtrabackup] cannot mkdir: 2 /backups/full_2025-08-18_00-35-01.895/
/scripts/backup.sh: line 30: /backups/last_full.txt: No such file or directory
[2025-08-18_00-35-01.893][FINISH full BACKUP]
/scripts/backup.sh: line 30: /backups/last_full.txt: No such file or directory
[2025-08-18_00-35-01.895][FINISH full BACKUP]
[2025-08-18_00-36-01.163][START incremental BACKUP]
[POC] Nenhum full encontrado, criando full primeiro.
[2025-08-18_00-36-01.167][START full BACKUP]
[POC] Criando FULL backup em /backups/full_2025-08-18_00-36-01.167
2025-08-18T00:36:01.187924-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized server arguments: --datadir=/var/lib/mysql 
2025-08-18T00:36:01.188189-00:00 0 [Note] [MY-011825] [Xtrabackup] recognized client arguments: --backup=1 --target-dir=/backups/full_2025-08-18_00-36-01.167 --host=db --user=root --password=* 
xtrabackup version 8.0.35-34 based on MySQL server 8.0.35 Linux (x86_64) (revision id: c8a25ff9)
250818 00:36:01  version_check Connecting to MySQL server with DSN 'dbi:mysql:;mysql_read_default_group=xtrabackup;host=db' as 'root'  (using password: YES).
Failed to connect to MySQL server: DBI connect(';mysql_read_default_group=xtrabackup;host=db','root',...) failed: Unknown MySQL server host 'db' (-2) at - line 1536.
2025-08-18T00:36:01.545780-00:00 0 [Note] [MY-011825] [Xtrabackup] Connecting to MySQL server host: db, user: root, password: set, port: not set, socket: not set
2025-08-18T00:36:01.848689-00:00 0 [ERROR] [MY-011825] [Xtrabackup] Failed to connect to MySQL server: Unknown MySQL server host 'db' (-2)
/scripts/backup.sh: line 30: /backups/last_full.txt: No such file or directory
[2025-08-18_00-36-01.167][FINISH full BACKUP]
